#Random- effect-model
#pooling the effect size

library(metafor)
library(meta)
library(dmetar)
library(tidyverse)
library(xlsx)

my_data <- my_data
glimpse(my_data)

#transforming SMD into OR
for(i in 1:#the size of my dataset){
if (Metric==Mean difference){
        SMD<-MD #mean difference#/SD} else {
    if (Metric==Standard mean difference){
#(SMD * 1.81)*2.71828183 <- OR} else{
      if (Metric== OR){
        break}
      
## calculatin the SD from my new OR 
#odds.ratio(OR, level=0.95,...) 
#...further arguments passed to or from other methods

#the analyses al all smaller MA (building a loop)

for(i in 1: #depends how big my file is)) {
    if (systematic_review_number==1) {
      m.bin.1<- metabin(event.e = events_t, 
                n.e = n_partc_t_arm,
                event.c = events_c,
                n.c = n_partc_c_arm,
                #studlab = author,
                data = my_data,
                sm = "OR",      # effect size metric, od for odds ratio amd RR for risk ratio
                method = "MH",  #Mantel-Haenszel
                MH.exact = TRUE,#indicating that we do not want that a continuity correction is used for the Mantel-Haenszel method
                fixed = FALSE,
                random = TRUE,
                method.tau = "PM",  #here to choose apropriate method to calculaze tau2!!
                hakn = TRUE,
                title = "Test.index")
summary(m.bin.1)} else {
      if (systematic_review_number ==2){
     m.bin.2<- metabin(event.e = events_t, 
                n.e = n_partc_t_arm,
                event.c = events_c,
                n.c = n_partc_c_arm,
                #studlab = author,
                data = my_data,
                sm = "OR",      # effect size metric, od for odds ratio amd RR for risk ratio
                method = "MH",  #Mantel-Haenszel
                MH.exact = TRUE,#indicating that we do not want that a continuity correction is used for the Mantel-Haenszel method
                fixed = FALSE,
                random = TRUE,
                method.tau = "PM",  #here to choose apropriate method to calculaze tau2!!
                hakn = TRUE,
                title = "Test.index")
summary(m.bin.2)   } else{ ....# depents how many systematic reviews will be included  
  #loops with data (repeat) 
#repeat 
#{
#statements
# if(condition){
#break #used to terminate the loop
}
}
#  
#probably I sould also have forest plot for all those MA??

#pooling all the odds ratios
m.bin<- metabin(event.e = events_t, 
                n.e = n_partc_t_arm,
                event.c = events_c,
                n.c = n_partc_c_arm,
                #studlab = author,
                data = my_data,
                sm = "OR",      # effect size metric, od for odds ratio amd RR for risk ratio
                method = "MH",  #Mantel-Haenszel
                MH.exact = TRUE,#indicating that we do not want that a continuity correction is used for the Mantel-Haenszel method
                fixed = FALSE,
                random = TRUE,
                method.tau = "PM",  #here to choose apropriate method to calculaze tau2!!
                hakn = TRUE,
                title = "Test.index")
summary(m.bin)

#As announced above, let us have a look if the method used to estimate tau2
#has an impact on the results. Here we re-run the analysis, but use the 
#restricted maximum likelihood estimator this time.

m.bin_update <- update.meta(m.bin, 
                method.tau = "REML")

#To retransform log-transformed effect sizes, 
#we have to exponentiate the value.

exp(m.bin_update$TE.random)

#the estimate of tau2

#m.bin_update$tau2

#assessing heterogeneity 


#Forest Plot

forest.meta(m.bin.index)
#sortvar = TE,    #order the results by effect size
predict = TRUE, 
print.tau2 = FALSE)
leftcols = c("TE", "seTE"))
#leftlabs = c("Author", "g", "SE"))

#layout generated by Cochrane's Review Manager 5
forest.meta(m.gen, layout = "RevMan5")

#ratio of odds (the odd ratio of pragmatic trials divided by the odds ratio
#of corresponding trials)

# first I need poold data for both index and corresponding trials 

for(i in 1:2){
  if(index_trial==TRUE){
m.bin.index<- metabin(event.e = events_t, 
                n.e = n_partc_t_arm,
                event.c = events_c,
                n.c = n_partc_c_arm,
                #studlab = author,
                data = my_data,
                sm = "OR",      # effect size metric, od for odds ratio amd RR for risk ratio
                method = "MH",  #Mantel-Haenszel
                MH.exact = TRUE,#indicating that we do not want that a continuity correction is used for the Mantel-Haenszel method
                fixed = FALSE,
                random = TRUE,
                method.tau = "PM",  #here to choose apropriate method to calculaze tau2!!
                hakn = TRUE,
                title = "Test.index")
summary(m.bin.index)} else {
    m.bin.corr<- metabin(event.e = events_t, 
                n.e = n_partc_t_arm,
                event.c = events_c,
                n.c = n_partc_c_arm,
                #studlab = author,
                data = my_data,
                sm = "OR",      # effect size metric, od for odds ratio amd RR for risk ratio
                method = "MH",  #Mantel-Haenszel
                MH.exact = TRUE,#indicating that we do not want that a continuity correction is used for the Mantel-Haenszel method
                fixed = FALSE,
                random = TRUE,
                method.tau = "PM",  #here to choose apropriate method to calculaze tau2!!
                hakn = TRUE,
                title = "Test.index")
summary(m.bin.corr)

#rOR<-m.bin.index/m.bin.corr


